ALTER TABLE `learnlanguage`.`t_vocabulary` ADD COLUMN `KANJI` VARCHAR(20) NULL DEFAULT NULL  AFTER `WORD` ;
ALTER TABLE `learnlanguage`.`t_listening` DROP COLUMN `CONTENT_TRANSLATE` ;
ALTER TABLE `learnlanguage`.`t_listening` ADD COLUMN `CONTENT` TEXT NULL DEFAULT NULL  AFTER `CONTENT_FILE` ;
ALTER TABLE `learnlanguage`.`t_listening` ADD COLUMN `LISTENING_TYPE` CHAR(1) NULL DEFAULT NULL  AFTER `LESSON_COURSE_ID` ;
ALTER TABLE `learnlanguage`.`t_kanji` ADD COLUMN `KUN_YOMI` VARCHAR(50) NULL DEFAULT NULL  AFTER `WORD` ;
ALTER TABLE `learnlanguage`.`t_kanji` ADD COLUMN `ON_YOMI` VARCHAR(50) NULL DEFAULT NULL  AFTER `WORD` ;