CREATE  TABLE `learnlanguage`.`T_LEARN` (

  `LEARN_ID` INT(11) NOT NULL AUTO_INCREMENT,

  `LESSON_ID` INT(11) NOT NULL ,

  `START_DATE` DATE NULL ,

  `END_DATE` DATE NULL ,

  `STATUS` TINYINT(1)  NULL ,

  `COURSE_STATUS` CHAR(6) NULL ,

  `EXAM_MARK` INT(5) NULL ,

  PRIMARY KEY (`LEARN_ID`) ,

  INDEX `T_LEARN-T_LESSON_COURSE` (`LESSON_ID` ASC) ,

  CONSTRAINT `T_LEARN-T_LESSON_COURSE`

    FOREIGN KEY (`LESSON_ID` )

    REFERENCES `learnlanguage`.`t_lesson` (`LESSON_ID` )

    ON DELETE NO ACTION

    ON UPDATE NO ACTION)

ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8

COLLATE = utf8_general_ci;

